/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alice;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

      Path alicePath  = Paths.get("alice_in_wonderland.txt");
      System.out.println(alicePath.toAbsolutePath());

      // Read the file - Scanner
      Scanner scanner = null;
      scanner = new Scanner(alicePath);

      String characterName = "Alice";
      HashMap<String, Integer> aliceMap = new HashMap<>();

      // Run logic on the file -> Look for Alice instances
      aliceMap.put(characterName, 0);
      while(scanner.hasNextLine()) {
        // Check every line for Alice
        String currentLine = scanner.nextLine();
        if(currentLine.contains(characterName)) {
          // If any instances, add to HashMap
          aliceMap.put(characterName, (aliceMap.get(characterName) + 1));
        }
      }

      //return how many lines we saw alice in
      System.out.println("Alice showed up in " + aliceMap.get(characterName) + " lines.");



      // BUFFERED READER EXAMPLE
      Path bufferedReaderAlicePath  = Paths.get("alice_in_wonderland.txt");
      BufferedReader reader = null;
      try {
        reader = Files.newBufferedReader(bufferedReaderAlicePath);
        String line = reader.readLine();
        while(line != null) {
          line = reader.readLine();
        }
      } catch(IOException ioe) {
        System.out.println("Error reading file: " + ioe.getMessage());
        ioe.printStackTrace();
      } finally {
        reader.close();
      }

      // THIS IS GOLD!! Choose this strategy!
      try(BufferedReader newReader = Files.newBufferedReader(bufferedReaderAlicePath)) {
        String line = newReader.readLine();
        while(line != null) {
          line = newReader.readLine();
        }
      } catch (IOException ioe) {
        System.out.println("Error reading file: " + ioe.getMessage());
        ioe.printStackTrace();
      }
    }
}
