/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pepperspalace;

import pepperspalace.animal.Domesticated;
import pepperspalace.animal.Ocelot;
import pepperspalace.animal.Sloth;
import pepperspalace.logger.ConsoleLogger;
import pepperspalace.logger.Logger;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        List<Integer> myArrayList = new ArrayList<Integer>();
        myArrayList.add(5);

        for(int i = 0; i < myArrayList.size(); i++) {
          System.out.println("array list at index " + i + ": " + myArrayList.get(i));
        }

        ConsoleLogger consoleLogger = new ConsoleLogger();
        doAThing("test from console", consoleLogger);

        Ocelot indi = new Ocelot("indi", 4, 2, "black");
        Sloth robo = new Sloth("robo", 2, 10, 4.6f);

      System.out.println(indi.backFlip());
      System.out.println(robo.backFlip());

      System.out.println("all domesticated animals trained for " + Domesticated.trainedFor);
    }

   public static void doAThing(String data, Logger logger) {
      logger.log(data);
    }

    public static void example(int myInt) throws IllegalArgumentException {
      throw new IllegalArgumentException("illegal argument was given");
    }
}
