/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.UnknownHostException;
import java.nio.Buffer;

public class App {
  public static void main(String[] args) throws IOException {
    // step 1: make url, connection
    URL url = new URL("https://www.s.tech/api/people/1");
    HttpURLConnection connection = (HttpURLConnection) url.openConnection();

    // step 2: set headers, check your response code, use a try catch to handle bad urls, and close your connection!
    try {
      connection.setRequestMethod("GET");
      int status = connection.getResponseCode();
      System.out.println(status);

      if (status == 200) {
        // if your response code is good, we'll do some stuff
        // step 3: get data as a stream
        InputStreamReader streamReader = new InputStreamReader(connection.getInputStream());

        // step 4: use BufferedReader to read the input (can also use streamReader.read())
        try(BufferedReader bufferedReader = new BufferedReader(streamReader)) {
          String line = bufferedReader.readLine();
          System.out.println(line);

          // step 5: need to create objects to convert formatted JSON from
          // step 5.5: use GSON to create your objects
          Gson gson = new Gson();
          Person person = gson.fromJson(line, Person.class);
          System.out.println(person.toString());
        }
      } else {
        // tell us what went wrong
        System.out.println("it exploded: " + status);
      }
    } catch(MalformedURLException mue) {
      System.out.println("bad url");
      mue.printStackTrace();
    } catch(IOException ioe) {
      System.out.println("problem with api");
      ioe.printStackTrace();
    }  finally {
      connection.disconnect();
    }

    // SECOND EXAMPLE WITH FORISMATIC QUOTES
    URL fUrl = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json");
    HttpURLConnection fConnection = (HttpURLConnection) fUrl.openConnection();

    try {
      fConnection.setRequestMethod("GET");
      int fStatus = fConnection.getResponseCode();

      if(fStatus == 200) {
        InputStreamReader fStreamReader = new InputStreamReader(fConnection.getInputStream());
        try(BufferedReader fBufferedReader = new BufferedReader(fStreamReader)) {
          String fLine = fBufferedReader.readLine();
          System.out.println(fLine);
          Gson fSon = new Gson();

        }
      } else {
        System.out.println("forismatic exploded: " + fStatus);
      }
    } catch(MalformedURLException mue) {
      System.out.println("bad url");
      mue.printStackTrace();
    } catch(IOException ioe) {
      System.out.println("problem with api");
      ioe.printStackTrace();
    }finally {
      connection.disconnect();
    }
  }
}
