/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package indisbbbakery;

import indisbbbakery.bakedGoods.Cupcake;

import java.util.ArrayList;

public class App {
    public String welcomeMessage() {
      return "Welcome to Indi's Baked Bean Bakery!";
    }

    public static void main(String[] args) {
      Bakery.advertisement();

      System.out.println("I'm a bakery goer and I am pretty the bakeries open at " + Bakery.OPEN_TIME);

      System.out.println(new App().welcomeMessage());

      Bakery indis = new Bakery(3, 300);

      indis.makeSale(1, 1);

      final ArrayList<Integer> myFinalArrayList = new ArrayList<>();
      myFinalArrayList.add(15);

      final int myFinalInt = 8;
      // myFinalInt = 10;  <-- NOT ALLOWED!!!

      for(int i = 0; i < args.length; i++) {
        System.out.println(args[i]);
      }
    }
}
