/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package indibeans;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void passedInNumberReturnsSameNumber() {
        Library sut = new Library();
        // assertTrue(sut.returnPassedInNumber(5) == 10);
        assertEquals(5, sut.returnPassedInNumber(5));
    }
}
