/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maps;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        ArrayList<String> students = new ArrayList<>();
        students.add("DaJon");
        students.add("Cameron");
        students.add("Dasha");
        students.add("Chris");
        students.add("Alex");
        students.add("Cameron");

      System.out.println("Students who answered a question: " + whoAnsweredQuestions(students));

      // Your favorite color
      HashMap<String, Integer> favColors = new HashMap<>();
      favColors.put("blue", 1);
      favColors.put("red", 1);
      favColors.put("green", 1);
      favColors.put("red", favColors.get("red") + 1);
      favColors.put("red", favColors.get("red") + 1);

      System.out.println("Favorite colors in the class: " + favColors);

    }

    public static HashSet<String> whoAnsweredQuestions(ArrayList<String> students) {
      HashSet<String> studentsWhoAnswered = new HashSet<>();

      for(int i = 0; i < students.size(); i++) {
        // if(!studentsWhoAnswered.contains(students.get(i))) {
          studentsWhoAnswered.add(students.get(i));
        // }
      }

      return studentsWhoAnswered;
    }
}
