/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swapi;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.MalformedInputException;

public class App {
  public static void main(String[] args) throws IOException {
    // step 1: create url, and a connection
    URL starURL = new URL("https://swapi.tech/api/people/10");
    HttpURLConnection starConnection = (HttpURLConnection) starURL.openConnection();

    // step 2: set our headers, check response code, use a try/catch to handle bad urls, close connection
    try {
      starConnection.setRequestMethod("GET");
      int starStatus = starConnection.getResponseCode();
      System.out.println(starStatus);

      if(starStatus == 200) {
        // do some stuff

        // step 3: get data as a stream
        InputStreamReader starStreamReader = new InputStreamReader(starConnection.getInputStream());

        // step 4: use BufferedReader to read the input (can also use starStreamReader.read())
        try(BufferedReader starBufferedReader = new BufferedReader(starStreamReader)) {
          String line = starBufferedReader.readLine();
          System.out.println(line);

          // step 5: create class(es) to convert formatted JSON to (come back when you're done)
          // step 5.5: use GSON to create your objects
          Gson starSon = new Gson();
          StarWarsPerson starWarsPerson = starSon.fromJson(line, StarWarsPerson.class);
          System.out.println(starWarsPerson.toString());
        }
      } else {
        // tell us what went wrong
        System.out.println("star was destroyed: " + starStatus);
      }

    } catch(MalformedURLException mue) {
      System.out.println("bad url");
      mue.printStackTrace();
    } catch(IOException ioe) {
      System.out.println("problem with api");
      ioe.printStackTrace();
    } finally {
      starConnection.disconnect();
    }
  }
}
