/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pepperspalace;

import org.junit.jupiter.api.Test;
import pepperspalace.animals.Narwhal;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void narwhalCanStab() {
      // arrange
      Narwhal jerry = new Narwhal("Jerry", 0, 5, 12.6f);
      String jerryStabString = "oh no, Jerry has attacked someone again";
      // act
      String actualOutput = jerry.stab();
      // assert
      assertEquals(jerryStabString, actualOutput);
    }
}
