/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unicorns;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
      System.out.println(new App().getGreeting());

      // writing primitives with GSON
      Gson gson = new Gson();
      gson.toJson(1); // ==> 1
      gson.toJson("abcd");       // ==> "abcd"
      int[] values = {1, 5, 10, 13, 14};
      gson.toJson(values);       // ==> [1]

      // fromJSON to Java --> need type
      String stringyArray = "[\"Blue\",\"Green\",\"Purple\"]";

      Integer one = gson.fromJson("1", Integer.class);
      Boolean notTrue = gson.fromJson("false", Boolean.class);
      String[] strArray1 = gson.fromJson("[\"abc\"]", String[].class);
      String[] strArray2 = gson.fromJson(stringyArray, String[].class);


      // OBJECTS
      ArrayList<String> colors = new ArrayList<>();
      colors.add("Blue");
      colors.add("Pink");
      // create a unicorn object and convert it to JSON
      Unicorn unicorn = new Unicorn(4, 6, true, colors);
      String jsonicorn = gson.toJson(unicorn);
      System.out.println(jsonicorn);

      String darkicorn = "{\"hornLength\":20,\"isMajestic\":true,\"colors\":[\"Dark\",\"Black\"]}";
      Unicorn darkicornRevived = gson.fromJson(darkicorn, Unicorn.class);
      System.out.println(darkicorn);
      System.out.println(darkicornRevived.toString());

      // Write JSON to File
      File unicornFileOut = new File("./app/src/main/resources/unicorn.json");
      try(FileWriter unicornFileWriter = new FileWriter(unicornFileOut)){
        gson.toJson(darkicornRevived, unicornFileWriter);
        System.out.println("test");
      } catch(IOException ioe) {
        System.out.println("Caught an IOException with stack trace:");
        ioe.printStackTrace();
      }

      // Read from a JSON File
      File unicornFile = new File("./app/src/main/resources/unicorn.json");
      FileReader unicornFileReader = new FileReader(unicornFile);
      Unicorn darkicornTwo = gson.fromJson(unicornFileReader, Unicorn.class);
      System.out.println(darkicornTwo.toString());
    }
}
